name: flutter_beautifull_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/thai.jpg
    - assets/italy.jpg
    - assets/japan.jpg
    - assets/lake.jpg
  fonts:
    - family: SF Pro Display
      fonts:
      - asset: fonts/SF-Pro-Display-Ultralight.otf
        weight: 100
      - asset: fonts/SF-Pro-Display-Thin.otf
        weight: 200
      - asset: fonts/SF-Pro-Display-Light.otf
        weight: 300
      - asset: fonts/SF-Pro-Display-Regular.otf
        weight: 400
      - asset: fonts/SF-Pro-Display-Medium.otf
        weight: 500
      - asset: fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: fonts/SF-Pro-Display-Heavy.otf
        weight: 800
      - asset: fonts/SF-Pro-Display-Black.otf
        weight: 900